# Generated by Django 3.1.1 on 2020-09-23 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.PositiveIntegerField(default=22, validators=[django.core.validators.MaxValueValidator(110), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='recipemagic',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='followers',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
