# Generated by Django 3.1.2 on 2020-10-06 20:14

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_path),
        ),
    ]
