# Generated by Django 3.1.1 on 2020-10-10 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201010_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='alreadyfollowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='followsystem',
            name='followed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
