# Generated by Django 3.1.1 on 2020-10-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200930_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
